### ISSUE TITLE
Error: Can't find app.py

### ISSUE THREAD

**Issue by msbhatt2018** [MapleFrogStudio/AlgorithmicTrading#6]
while running the command python app.py --help, getting an error can't find app.py
please let me know if I am missing any steps

**Comment by poivronjaune** [comment]
Sorry @msbhatt2018, refactored a lot of stuff and did not update the readme file.  Please be aware this is on ongoing experiment and we will sometimes break some stuff :) You can use python cli.py --help instead of app.py.
